name: Build and deploy Python app to Azure Web App - chest-xray-classification

on:
  push:
    branches:
      - Project-Revisit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          # Remove the virtual environment directory to save space
          rm -rf env
          zip -r code.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chest-xray-classification'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./code.zip

      - name: Run custom deployment script
        run: bash deploy.sh
