# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chest-xray-calssification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_51c467328a704bab816c6e27ae88daa6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_82ce024b813c48cebec6d8707f345547 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_51c467328a704bab816c6e27ae88daa6 }}/hub.docker.com/justakris/chest-xray-classification-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chest-xray-calssification'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14dba549525f46ae98920bcc605c3a76 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_51c467328a704bab816c6e27ae88daa6 }}/hub.docker.com/justakris/chest-xray-classification-app:${{ github.sha }}'