name: Deploy Chest X-Ray Classification Flask App to Render via DockerHub

on:
  # push:
  #   branches: [ "main", "Project-Revisit" ]
  # pull_request:
  #   branches: [ "main", "Project-Revisit" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t justakris/chest-xray-classification-app:latest .

      - name: Push Docker Image
        run: |
            docker push justakris/chest-xray-classification-app:latest

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_DOCKER }}
          api-key: ${{ secrets.RENDER_API_KEY }}
